---
Name: deploynautconfig
---
Debug:
  friendly_error_httpcode: true
MySQLDatabase:
  connection_charset: "utf8"
Deploynaut:
  snapshot_post_address: 'Operations Team<br />Level 5,<br />101-103 Courtenay Place<br />Wellington<br />6011<br />New Zealand'
Email:
  admin_email: 'support@silverstripe.com'
AdminRootController:
  default_panel: 'DNAdmin'
DNProject:
  defaults:
    DiskQuotaMB: "1024"
Group:
  belongs_many_many:
    "Projects": "DNProject"
GridFieldDetailForm_ItemRequest:
  extensions:
    - FrontendLink
Injector:
  DNData:
    properties:
      # Set EnvironmentDir and KeyDir to absolute paths in your live project
      EnvironmentDir: "../../deploynaut-resources/envs"
      KeyDir: "../../deploynaut-resources/gitkeys"
      SignalDir: "../../deploynaut-resources/signals"
      # Set to an absolute path, or a relative path to append to BASE_PATH
      DataTransferDir: "assets/transfers"
      # User to run commands as locally
      GitUser: ''
  DeploymentBackend:
    class: CapistranoDeploymentBackend
  Finite\StateMachine\StateMachine:
    class: Finite\StateMachine\StateMachine
    type: prototype
  LDAPChangePasswordForm:
    class: 'DeploynautLDAPChangePasswordForm'
  EventEmitter:
    class: 'League\Event\Emitter'
  SS_Datetime:
    class: 'SS_Datetimezone'

StateMachineFactory:
  handlers:
    DNDeployment:
      new:
        DNDeploymentHandlers: onNew
      submit:
        DNDeploymentHandlers: onSubmit
      approve:
        DNDeploymentHandlers: onApprove
      reject:
        DNDeploymentHandlers: onReject
      queue:
        DNDeploymentHandlers: onQueue
      abort:
        DNDeploymentHandlers: onAbort
Member:
  extensions:
    - DeploynautMemberExtension
File:
  extensions:
    - DeploynautFileExtension
Security:
  extensions:
    - DeploynautSecurityExtension
